# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'copiar' -Path (Join-Path (Join-Path $toolsDir 'bin') 'copiar.bat')
Install-BinFile -Name 'copiard' -Path (Join-Path (Join-Path $toolsDir 'bin') 'copiard.bat')
